#!/bin/bash

git checkout master
git checkout deploy
git merge master
git checkout behindthestation
git merge deploy
git checkout deploy
git checkout adultmediafactory
git merge deploy
git checkout master
